const projects = [
  {
    id: 'project3',
    title: 'Soda 3D Website',
    img: '/project3/project3.png',
    link: '/projects/project3',
    date: '2026',
    liveLink: 'https://soda-tan-psi.vercel.app/',
    company: 'Personal Project',
    primary: '#1B2040',
    accentColor: '#D4F97F',
    secondary: '#F0F8E8',
    fillColor: '#E8F5D4',
    menuColor: '#FF6B35',
    menuFontColor: '#FFFFFF',
    fluidColor: '#FF6B35',
    images: [
      {
        src: '/project3/project3.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Soda is an interactive web application developed using the modern SPA (Single Page Application) concept, delivering a browsing experience that is fast, lightweight, and seamless.',
      'Featuring user authentication and a dynamic navigation system, this application allows users to efficiently access various features within a single integrated page.',
      'The primary development focus lies in performance, clean UI, and an intuitive user experience, positioning Soda as a representation of modern web technology implementation that is both scalable and user-friendly.',
    ],
  },

  {
    id: 'project1',
    title: 'Coffee Shop',
    img: '/project1/1.webp',
    link: '/projects/project1',
    date: '2025 Desember',
    company: 'Personal Project',
    liveLink: 'https://kopi-klasik.vercel.app/',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Developed a Coffee Shop Progressive Web App using React and TypeScript with modern frontend architecture.',
      'Implemented responsive UI with Tailwind CSS, state management using Zustand, and API data handling with React Query.',
      'Integrated Supabase for backend services and authentication while building reusable components and admin dashboard features.',
    ],
  },
  {
    id: 'project2',
    title: 'Verflix (Streaming Vidio)',
    img: '/project2/project2.png',
    link: '/projects/project2',
    date: '2024',
    company: 'Personal Project',
    liveLink: 'https://verflix-seven.vercel.app/',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/project2.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Developed a video streaming Progressive Web App (PWA) inspired by Netflix using React and TypeScript with a modern frontend architecture.',
      'Implemented a responsive and interactive UI using Tailwind CSS, along with state management using Zustand and efficient data fetching with React Query.',
      'Integrated Supabase for backend services, including authentication, database management, and real-time features, while building reusable components and implementing features such as video search, watchlist (My List), and user notification system.',
    ],
  },
];
export default projects;
