const projects = [
  {
    id: 'project3',
    title: 'Kedai Sepatu',
    img: '/project3/project3.png',
    link: '/projects/project3',
    date: '2024',
    liveLink: 'https://kedai-sepatu.vercel.app/',
    company: 'Personal Project',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/project3.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Kedai Sepatu is a modern e-commerce web application designed to provide a seamless and user-friendly online shopping experience for footwear. The platform allows users to explore a curated collection of shoes, ranging from casual to sporty styles, through a clean and interactive interface.',
      'The website features product catalog browsing, search functionality, and a fully responsive design to ensure accessibility across desktop and mobile devices. It is built with a strong focus on performance, usability, and intuitive UI/UX to enhance user engagement and conversion.',
      'This project was developed using modern web technologies such as React, TypeScript, and Tailwind CSS, with a clean architecture approach that separates UI and business logic to ensure scalability and maintainability.',
    ],
  },

  {
    id: 'project1',
    title: 'Coffee Shop',
    img: '/project1/1.webp',
    link: '/projects/project1',
    date: '2025 Desember',
    company: 'Personal Project',
    liveLink: 'https://kopi-klasik.vercel.app/',
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/3.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: false,
      },
    ],
    desc: [
      'Developed a Coffee Shop Progressive Web App using React and TypeScript with modern frontend architecture.',
      'Implemented responsive UI with Tailwind CSS, state management using Zustand, and API data handling with React Query.',
      'Integrated Supabase for backend services and authentication while building reusable components and admin dashboard features.',
    ],
  },
  {
    id: 'project2',
    title: 'Verflix (Streaming Vidio)',
    img: '/project2/project2.png',
    link: '/projects/project2',
    date: '2024',
    company: 'Personal Project',
    liveLink: 'https://verflix-seven.vercel.app/',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/project2.png',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Developed a video streaming Progressive Web App (PWA) inspired by Netflix using React and TypeScript with a modern frontend architecture.',
      'Implemented a responsive and interactive UI using Tailwind CSS, along with state management using Zustand and efficient data fetching with React Query.',
      'Integrated Supabase for backend services, including authentication, database management, and real-time features, while building reusable components and implementing features such as video search, watchlist (My List), and user notification system.',
    ],
  },
];
export default projects;
